"""SQUAT membrane-state quantization with snnTorch reference semantics."""

from __future__ import annotations

import math

import torch
import torch.nn as nn


def threshold_centered_levels(
    *,
    num_bits: int = 4,
    threshold: float = 1.0,
    lower_limit: float = 0.0,
    upper_limit: float = 0.2,
    multiplier: float = 0.5,
    dtype: torch.dtype = torch.float32,
) -> torch.Tensor:
    """Return the non-uniform levels generated by snnTorch ``state_quant``.

    The seemingly unusual split and endpoint behavior are deliberate.  This
    is a direct, compact reproduction of the public threshold-centered branch
    used by SQUAT, including its exclusion of the threshold itself.
    """

    if num_bits <= 0:
        raise ValueError("num_bits must be positive")
    if threshold <= 0:
        raise ValueError("threshold must be positive")
    if lower_limit < 0 or upper_limit < 0:
        raise ValueError("state limits must be non-negative")
    if not 0 < multiplier < 1:
        raise ValueError("multiplier must be in (0, 1)")

    maximum = threshold + threshold * upper_limit
    minimum = -(threshold + threshold * lower_limit)
    number = 2 << (num_bits - 1)
    overall_range = maximum - minimum
    lower_range = threshold - minimum
    upper_range = maximum - threshold
    lower_count = math.floor(number * lower_range / overall_range)
    upper_count = number - lower_count

    values: list[float] = []
    if lower_count:
        lower_sum = sum(multiplier**j for j in reversed(range(lower_count)))
        lower_room = lower_sum / lower_range
        value = minimum
        for j in range(lower_count):
            values.append(value)
            value += multiplier**j / lower_room

    if upper_count:
        upper_sum = sum(multiplier**j for j in reversed(range(upper_count)))
        upper_room = upper_sum / upper_range
        value = threshold
        for j in reversed(range(upper_count)):
            value += multiplier**j / upper_room
            values.append(value)

    levels = torch.tensor(values, dtype=dtype)
    if levels.numel() != number or not bool(torch.all(levels[1:] > levels[:-1])):
        raise RuntimeError("invalid threshold-centered level construction")
    return levels


class _NearestLevelSTE(torch.autograd.Function):
    @staticmethod
    def forward(ctx: object, value: torch.Tensor, levels: torch.Tensor) -> torch.Tensor:
        # ``torch.min(abs(...))`` in the reference chooses the lower level on
        # exact ties because levels are ascending. bucketize(right=False)
        # reproduces that behavior without materializing [..., 16].
        local_levels = levels.to(device=value.device, dtype=value.dtype)
        midpoints = (local_levels[:-1] + local_levels[1:]) * 0.5
        indices = torch.bucketize(value.contiguous(), midpoints, right=False)
        return local_levels[indices]

    @staticmethod
    def backward(ctx: object, grad_output: torch.Tensor) -> tuple[torch.Tensor, None]:
        return grad_output.clone(), None


class ThresholdCenteredStateQuantizer(nn.Module):
    """Four-bit non-uniform state fake quantizer with identity STE."""

    def __init__(
        self,
        *,
        num_bits: int = 4,
        threshold: float = 1.0,
        lower_limit: float = 0.0,
        upper_limit: float = 0.2,
        multiplier: float = 0.5,
    ) -> None:
        super().__init__()
        levels = threshold_centered_levels(
            num_bits=num_bits,
            threshold=threshold,
            lower_limit=lower_limit,
            upper_limit=upper_limit,
            multiplier=multiplier,
        )
        self.register_buffer("levels", levels, persistent=False)
        self.num_bits = int(num_bits)
        self.threshold = float(threshold)
        self.lower_limit = float(lower_limit)
        self.upper_limit = float(upper_limit)
        self.multiplier = float(multiplier)

    def forward(self, value: torch.Tensor) -> torch.Tensor:
        return _NearestLevelSTE.apply(value, self.levels)

